# - Ajouter 2 workflow
#     - Créer un workflow qui affiche un message en echo lors d'un fork de votre projet.
#     - Créer un workflow qui lors du déclenchement d'une issue envoie un message du type : `Bonjour nom_auteur, nous avons bien pris en compte votre problème du nom de : nom_issue`
#     - Utilisez des variables d'environnement.

name: issue workflow

on:
  issues:
    types: opened
    
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: gh issue comment $ISSUE_URL -b "Bonjour $ISSUE_AUTHOR, nous avons bien pris en compte pour problème du nom de $ISSUE_TITLE"