# - Ajouter 2 workflow
#     - Créer un workflow qui affiche un message en echo lors d'un fork de votre projet.
#     - Créer un workflow qui lors du déclenchement d'une issue envoie un message du type : `Bonjour nom_auteur, nous avons bien pris en compte votre problème du nom de : nom_issue`
#     - Utilisez des variables d'environnement.

name: Issue Workflow

on:
  issues:
    types: opened

jobs:
  commentaire:
    runs-on: ubuntu-latest
    steps:
      - name: Réponse à l'issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.url }}
        run: gh issue comment $ISSUE_URL --body "Merci pour votre message"
      