# - Ajouter 2 workflow
#     - Créer un workflow qui affiche un message en echo lors d'un fork de votre projet.
#     - Créer un workflow qui lors du déclenchement d'une issue envoie un message du type : `Bonjour nom_auteur, nous avons bien pris en compte votre problème du nom de : nom_issue`
#     - Utilisez des variables d'environnement.

name: Issue Workflow

on:
  issues:
    types: [opened]

jobs:
  commentaire:
    runs-on: ubuntu-latest
    steps:
      - name: Réponse à l'issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          MESSAGE="Bonjour $ISSUE_AUTHOR, nous avons bien pris en compte votre problème du nom de : $ISSUE_TITLE"
          gh issue comment $ISSUE_NUMBER --body "$MESSAGE"