name: Workflow push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: mise en cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Installation des dépendances
        run: mvn install

      - name: Build de l'application
        run: mvn package

      - name: test de l'application
        run: mvn test
        continue-on-error: true

      - name: Upload artefact
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build_app
          path: target/*.jar