# Nom pour le workflow
name: Workflow Push

# On précise quel est le déclencheur de notre workflow
on: push

jobs:
  # On définit la 1re action à exécuter :
  premier-job:
    # Spécifier le système d'exploitation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Configurer Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    - name: Construire et tester avec Maven
      run: mvn -B clean install -Dfile.encoding=UTF-8
    - name: Exécuter l'application Spring Boot
      run: mvn spring-boot:run -Dfile.encoding=UTF-8

