name: Workflow Push

on: push

jobs:
  premier-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Mise en cache des dépendances Maven
      uses: actions/cache@v3.3.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          ${{ runner.os }}-

    - name: Vérifier le cache Maven
      run: ls -la ~/.m2/repository

    - name: Afficher l'environnement de test
      run: |
        java -version
        mvn -version
        echo $JAVA_HOME
        echo $PATH

    - name: Vérifier le répertoire Maven local
      run: mvn help:evaluate -Dexpression=settings.localRepository

    - name: Construire l'application
      run: mvn clean package -Dtest=EtudiantApplicationTests

    - name: Upload de l'artéfact
      uses: actions/upload-artifact@v3
      with:
        name: mon-application
        path: target/*.jar
