# Nom pour le workflow
name: Workflow Push

# On précise quel est le déclencheur de notre workflow
on: push

jobs:
  # On définit la 1re action à exécuter :
  premier-job:
    # Spécifier le système d'exploitation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Afficher l'environnement de test
      run: |
        java -version
        mvn -version
        echo $JAVA_HOME
        echo $PATH
