# Nom pour le workflow
name: Workflow Push

# On précise quel est le déclencheur de notre workflow
on: push

jobs:
  # On définit la 1re action à exécuter :
  premier-job:
    # Spécifier le système d'exploitation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4 # https://github.com/marketplace/actions/setup-java-jdk
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Afficher l'environnement de test
      run: |

        java -version # Afficher la version de Java installée
        mvn -version # Afficher la version de Maven installée
        echo $JAVA_HOME # Afficher le chemin d'installation de Java
        echo $PATH # Afficher les chemins d'accès du système